// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3i4L2jn5XOzIEHDYgyVR3AnnbbYwV5_E',
    appId: '1:730051416978:web:90ccf05aa97816a1ab274b',
    messagingSenderId: '730051416978',
    projectId: 'taxi-finder-93d36',
    authDomain: 'taxi-finder-93d36.firebaseapp.com',
    storageBucket: 'taxi-finder-93d36.appspot.com',
    measurementId: 'G-05WWZBZHPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK5l1y8dAvLMlvbcaNtR2va70bs8yTJHM',
    appId: '1:730051416978:android:98b9395574db4c01ab274b',
    messagingSenderId: '730051416978',
    projectId: 'taxi-finder-93d36',
    storageBucket: 'taxi-finder-93d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSfu7OrRphJUxs1X-zHf_ti4XN4o7hPg',
    appId: '1:730051416978:ios:9a60e0e93c868347ab274b',
    messagingSenderId: '730051416978',
    projectId: 'taxi-finder-93d36',
    storageBucket: 'taxi-finder-93d36.appspot.com',
    iosBundleId: 'com.example.taxiFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSfu7OrRphJUxs1X-zHf_ti4XN4o7hPg',
    appId: '1:730051416978:ios:9a60e0e93c868347ab274b',
    messagingSenderId: '730051416978',
    projectId: 'taxi-finder-93d36',
    storageBucket: 'taxi-finder-93d36.appspot.com',
    iosBundleId: 'com.example.taxiFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3i4L2jn5XOzIEHDYgyVR3AnnbbYwV5_E',
    appId: '1:730051416978:web:0515fc5cb09b923dab274b',
    messagingSenderId: '730051416978',
    projectId: 'taxi-finder-93d36',
    authDomain: 'taxi-finder-93d36.firebaseapp.com',
    storageBucket: 'taxi-finder-93d36.appspot.com',
    measurementId: 'G-02WYBW6G98',
  );
}
